version: "3.8"

services:
  app:
    container_name: cr-dev
    stdin_open: true
    image: cr-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3099:3000

